### PR TITLE
#302 - activities page

### LINKED ISSUE #302: Activities Page
There is a need to update activities & single activity page.
[Design](https://www.figma.com/design/sdPYb47iLBwsA2FQMIu5BR/Blumilk?node-id=1-4&t=wanfeKvRzxuAEa1k-0)
image
image

### PR DESCRIPTION
**Pull request by AleksandraKozubal**
Apart from the changes on activities page and activity page, I also cleaned up home controller, fixed navigation hover and added possibility to hide big bubbles.
It should close #302.

[Desktop design](https://www.figma.com/design/sdPYb47iLBwsA2FQMIu5BR/Blumilk?node-id=1-4&t=wanfeKvRzxuAEa1k-0)
[Mobile design](https://www.figma.com/design/2QnCtqnBUqCoBnoys47J9d/MOBILE?node-id=29-6646&t=8WK1eUEBn4XXGblV-0)
Desktop activities page:
image
Desktop activity page:
image
Mobile activities page:
image
Mobile activity page:
image

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. Missing empty state? :thinking:  Or maybe we should hide tags that has on activities?

image

2. It's more UX question - now, when activity has no tags, it's only in "Wszystkie" tab. Is it okay for us or we should have some category for not tagged activities? 

3. When I add activity without English description, I see error that description is required, but I can't fill this field

image

**Comment by EwelinaSkrzypacz** [comment]
Conflicts

**Comment by AleksandraKozubal** [comment]
> 1. Missing empty state? 🤔  Or maybe we should hide tags that has on activities?
> 
> 
> [image](https://private-user-images.githubusercontent.com/56546832/355815919-40bf0cae-432f-45cf-85f9-1481b85e04b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQ3OTQsIm5iZiI6MTcyMzU0NDQ5NCwicGF0aCI6Ii81NjU0NjgzMi8zNTU4MTU5MTktNDBiZjBjYWUtNDMyZi00NWNmLTg1ZjktMTQ4MWI4NWUwNGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTRjODRkMjM0YjkyNDQxNzM3ZWIzMDNhN2VkNWEzNTBkZjQ0MWI4ZDYyNDQ4Y2RhNjdmZmRhMDIwYzE1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SQ9yzSJEz7FLrt01tHWBYYSuMdurUKeyP-1OJzDJhMk)
> 
> 2. It's more UX question - now, when activity has no tags, it's only in "Wszystkie" tab. Is it okay for us or we should have some category for not tagged activities?
> 
>3. When I add activity without English description, I see error that description is required, but I can't fill this field
> 
> 
> [image](https://private-user-images.githubusercontent.com/56546832/355817276-914b9e80-ef25-4c73-a95b-1a51adb6022a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQ3OTQsIm5iZiI6MTcyMzU0NDQ5NCwicGF0aCI6Ii81NjU0NjgzMi8zNTU4MTcyNzYtOTE0YjllODAtZWYyNS00YzczLWE5NWItMWE1MWFkYjYwMjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZWZhMDJjYzVjZDE3NDZhYmMzZmM3Y2YzNDBhOTJjM2YwNmVlNGIxN2YwMjhkYzJhMzc1NTkzZGZmZDMyY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iQsrfqu15AmcLkA6hSoLPbsl4QAdcfbTrcX115RSDic)

1.now they are hidden
2.In my opinion it's okat that they're only in all tag.
3.created issue for that

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. I have some error, when I'm doing like this: 

- I created tag and check this tag as main
- I created activity with this tag and the activity is shown on the page
- I go to admin panel and I uncheck "Oznacz jako główny" my tag
- I go to activity show and I click my tag
- I see error

image

2. I created tag "mój super tag" but on show activity page I see it uppercase like

image

3. On website we have "Aktywności" but on admin panel we have "Aktualności". Can we unify that?

**Comment by AleksandraKozubal** [comment]
> 1. I have some error, when I'm doing like this:
> 
> 
>     * I created tag and check this tag as main
> 
>     * I created activity with this tag and the activity is shown on the page
> 
>     * I go to admin panel and I uncheck "Oznacz jako główny" my tag
> 
>     * I go to activity show and I click my tag
> 
>     * I see error
> 
> 
> [image](https://private-user-images.githubusercontent.com/56546832/357377545-a46f169a-1cca-45ac-8cf3-67c25f7531ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDY3NDMsIm5iZiI6MTcyMzU0NjQ0MywicGF0aCI6Ii81NjU0NjgzMi8zNTczNzc1NDUtYTQ2ZjE2OWEtMWNjYS00NWFjLThjZjMtNjdjMjVmNzUzMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMWM5MmZhNTFkNzI4MDllNzViYmZkMmViNzc2NjdjNDdkZjcxZTAyNTIwZmUzNmZiMjI1NTViNzRiMmFiNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nll-toZN0EbMcViaSUWXPkRBbuLUrf8xIj06dWRmUpU)
> 
>2. I created tag "mój super tag" but on show activity page I see it uppercase like
> 
> 
> [image](https://private-user-images.githubusercontent.com/56546832/357377990-972cd263-3239-4863-80f9-d0d8982e2387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDY3NDMsIm5iZiI6MTcyMzU0NjQ0MywicGF0aCI6Ii81NjU0NjgzMi8zNTczNzc5OTAtOTcyY2QyNjMtMzIzOS00ODYzLTgwZjktZDBkODk4MmUyMzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZjcwYmUwMjZhMGUzZjRjODYyYTczYzI3MDQ0MmVlYTViZDU3N2I2OGZiNTZjZGMzM2Q5MDhlMmQzMDU3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MBQqMRl53KAISIrqcadYTi1XVKqG-pMqjFCcXngi53o)
> 
>3. On website we have "Aktywności" but on admin panel we have "Aktualności". Can we unify that?

1,2. fixed 
3.unified

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]

**Pull request merged**
