### PR TITLE
#183 - UX writing

### LINKED ISSUE #183: UX writing improvements
I would like to review all texts on our website and improve them UX-wise wherever possible.

### PR DESCRIPTION
**Pull request by EwelinaLasowy**
This should close #183.

Changes:
- better "Contact" page:

Before:
image

After:
image

- better descriptions on "Partnership" page

Overall, I didn't change a lot of texts, because they are okay.

### CODE REVIEW

**Review by krzysztofrewak — APPROVED** [review]

**Review by krzysztofrewak — DISMISSED** [review]

**Review by kamilpiech97 — APPROVED** [review]

**Comment by EwelinaLasowy** [comment]
Badges are not correctly showing - @kamilpiech97 will take care of this

**Comment by kamilpiech97** [comment]
> Badges are not correctly showing - @kamilpiech97 will take care of this

Build badge working but badge with check not working properly, we have pending status on main.
image
i think, we will remove that badge.

What do u think @krzysztofrewak ?

**Review by EwelinaLasowy — COMMENTED** [review]
Can we make this badge "build" with GitHub icon? Like we have "last commit badge"? And this badge should be named "deploy", no "build" - or we can't change name?

**Comment by krzysztofrewak** [comment]
> > Badges are not correctly showing - @kamilpiech97 will take care of this
> 
> Build badge working but badge with check not working properly, we have pending status on main. image i think, we will remove that badge.
> 
> What do u think @krzysztofrewak ?

We can remove that, but please check why the first badge has different style than others.

**Comment by kamilpiech97** [comment]
> > > Badges are not correctly showing - @kamilpiech97 will take care of this
> > 
> > 
> > Build badge working but badge with check not working properly, we have pending status on main. image i think, we will remove that badge.
> > What do u think @krzysztofrewak ?
> 
> We can remove that, but please check why the first badge has different style than others.

Fixed

**Review by krzysztofrewak — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]

**Pull request merged**
