### PR TITLE
#222 - activities crud

### LINKED ISSUE #222: [Dashboard] Activities
We should implement CRUD for activities (Aktualności) page on our website.

Activity should have fields like that:
- photo,
- title
- subtitle (optional)
- text/description
- created_at/published_at

Activity should be created for two languages - `pl` and `en`.

### PR DESCRIPTION
**Pull request by kamilpiech97**
Should close #222.

Added Activity model and CRUD views in admin panel. Some of activity fields are translatable via [laravel-translatable](https://spatie.be/docs/laravel-translatable/v6/introduction).

Preview of create view:
image

### CODE REVIEW

**Comment by kamilpiech97** [comment]
> 1. When I run `php artisan migrate:fresh --seed` I see error
> 
> image
> 
> As we talked with @kamilpiech97 we have to add empty folder `activities`
> 
> 2. Date on view/edit activity should be in Polish format (dd.mm.rrrr) - now it is like mm/dd/rrrr
> 
> image
> 
> 3. AFAIK the admin panel will be only in Polish, so we should show on index activities list title in Polish (now we show in English)
> 
> image

1, 2. fixed
3. should be done in next PR, filament has some connected stuff with translating and nice will be do this in new PR

**Review by EwelinaSkrzypacz — COMMENTED** [review]
For me date is still in format mm/dd/yyyy

image

**Review by EwelinaSkrzypacz — DISMISSED** [review]

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. Filters for dates doesn't work - for example I created an activity with publish date 11.04.2024 and I choose filters from 08.04.2024 to 08.04.2024, so I shouldn't see the activity, but it is

image

2. I think we should add sorting - by date asc and desc?

3. "The data publikacji field is required unless opublikowane is in 1." - this is validation message, when user check "Opublikowane" but doesn't fill date - can we write this somehow better? Like "Pole data publikacji jest wymagane, jeżeli została zaznaczona opcja Opublikowane" or something like that. We can also leave this to pr related to translations, it can be treated as reminder.

4. Can we add search input?

**Comment by kamilpiech97** [comment]
> 1. Filters for dates doesn't work - for example I created an activity with publish date 11.04.2024 and I choose filters from 08.04.2024 to 08.04.2024, so I shouldn't see the activity, but it is
> 
> image
> 
> 2. I think we should add sorting - by date asc and desc?
> 3. "The data publikacji field is required unless opublikowane is in 1." - this is validation message, when user check "Opublikowane" but doesn't fill date - can we write this somehow better? Like "Pole data publikacji jest wymagane, jeżeli została zaznaczona opcja Opublikowane" or something like that. We can also leave this to pr related to translations, it can be treated as reminder.
> 4. Can we add search input?

1, 2. fixed
3. I will do it in language PR or connected PR with i18n stuff
4. added

**Review by EwelinaSkrzypacz — APPROVED** [review]
:+1:

**Pull request merged**
