### PR TITLE
- contact page and footer tweaks

### PR DESCRIPTION
**Pull request by krzysztofrewak**
In this PR I changed two little things:

1. Added country to address in contact page (plus changed PascalCase to snake_case in one translation key):
image

2. Added source code link in footer and adjusted padding:
image

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
And after speaking with Natalia:

1. Can we change "Blumilk sp. z o.o." to just "Blumilk"?
2. Can we show on mobile links beneath, but without this |? 
Something like we have on old page


image

**Comment by krzysztofrewak** [comment]
@EwelinaSkrzypacz, please check new changes.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
On desktop, we still have "Blumilk sp. z o.o."

image

**Review by EwelinaSkrzypacz — APPROVED** [review]
As we spoke, on desktop we leave full name of company.

**Review by dawidrudnik — APPROVED** [review]

**Pull request merged**
