### PR TITLE
- logo fix

### PR DESCRIPTION
**Pull request by EwelinaSkrzypacz**
In this pr I fixed logo size on middle resolution. Also I changed some logos.

Now it looks like this

image

### CODE REVIEW

**Review by krzysztofrewak — APPROVED** [review]

**Review by AleksandraKozubal — APPROVED** [review]

**Comment by krzysztofrewak** [comment]
@EwelinaSkrzypacz, two logos are missing after changes.

obraz

**Comment by mtracz** [comment]
@krzysztofrewak 
Looks fine on my side (chrome).
image

**Comment by krzysztofrewak** [comment]
Same thing is on mobile Safari: 

image

**Comment by EwelinaSkrzypacz** [comment]
IN my Firefox browser it looks good.

image

**Comment by EwelinaSkrzypacz** [comment]
I will try to fix this issue on Safari :eyes:

**Pull request merged**
