### PR TITLE
- redirect www to non-www on prod

### PR DESCRIPTION
**Pull request by mtracz**
This PR adds permanent redirect (301) from www to non-www on prod env.

### CODE REVIEW

**Comment by kamilpiech97** [comment]
Old website was on `www.blumilk.pl`

**Comment by mtracz** [comment]
> Old website was on `www.blumilk.pl`

And what is the problem?

1. We have CNAME www.blumilk.pl to blumilk.pl
2. No we are adding permanent redirect from www.blumilk.pl to blumilk.pl

Both domains will work and route to our site.

**Review by Blusia — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Comment by mtracz** [comment]
@krzysztofrewak 
I marked it as draft because for me it was unclear if we want this or not.
But it looks like it will be better to do permanent redirect from www to non-www from SEO perspectives.

**Comment by mtracz** [comment]
Looks fine
image

**Pull request merged**
